language: ruby
cache:
- bundler
script:
  - bundle exec middleman build --clean
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN $ Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false
